### ISSUE TITLE
Umbrella issue for rich data grid

### ISSUE THREAD

**Issue by miyconst** [handsoncode-apps/InvoiceDemo#24]
- [ ] [Add possibility to restore hot-table layout on page load](https://github.com/handsoncode-apps/InvoiceDemo/issues/22)
- [ ] [Add possibility to save current hot-table layout](https://github.com/handsoncode-apps/InvoiceDemo/issues/21)
- [x] [Add possibility to change column order by dragging](https://github.com/handsoncode-apps/InvoiceDemo/issues/20)
- [ ] [Add possibility to hide/show columns](https://github.com/handsoncode-apps/InvoiceDemo/issues/19)
- [x] [Add possibility to resize columns](https://github.com/handsoncode-apps/InvoiceDemo/issues/18)
- [x] [Add hot-table context menu with Delete & Insert actions](https://github.com/handsoncode-apps/InvoiceDemo/issues/17)
- [x] [Pagination logic should be on server side](https://github.com/handsoncode-apps/InvoiceDemo/issues/16)
- [x] [Sorting should be on server side and should apply over all pages](https://github.com/handsoncode-apps/InvoiceDemo/issues/34)

**Comment by miyconst** [comment]
@jakubklekota are there any progress on this issue so far?

**Comment by miyconst** [comment]
cc @warpech

**Comment by jakubklekota** [comment]
@miyconst @warpech,
Currently working on:

- [Add hot-table context menu with Delete & Insert actions](https://github.com/handsoncode-apps/InvoiceDemo/issues/17)

- [Add possibility to save current hot-table layout](https://github.com/handsoncode-apps/InvoiceDemo/issues/21)

- [Add possibility to restore hot-table layout on page load](https://github.com/handsoncode-apps/InvoiceDemo/issues/22)
At end of day will be finished I hope

**Comment by jakubklekota** [comment]
@miyconst @warpech, - sorry, but this issue:
- [Add hot-table context menu with Delete & Insert actions](https://github.com/handsoncode-apps/InvoiceDemo/issues/17)

requires more time than I thought

**Comment by miyconst** [comment]
>requires more time than I thought

It might be replaced by "Delete" and "Insert" buttons for now. Others features are more important.

**Comment by jakubklekota** [comment]
@miyconst Could you pull newest version of the invoicedemo from GH and check it ? Currently all bugs was repair and tested by me and Krzysztof.

**Comment by miyconst** [comment]
Just did so.

**Comment by miyconst** [comment]
I have added another very important issue https://github.com/handsoncode-apps/InvoiceDemo/issues/34.

**Comment by warpech** [comment]
This issue duplicates https://github.com/handsoncode-apps/InvoiceDemo/issues/39 as well as the email discussion. Closing.
